config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  resources :users

  resources :topics do
    resources :replies
  end

  # namespace :wechat do
  #   resources :records
  # end

  resource :wechat, only: [:show, :create]


  get 'vue_learn' => 'home#vue_learn'
  get 'position' => 'home#position'

  namespace :v1 do
    post '/login', to: 'sessions#create'

    resources :topics, only: [:index]
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 30 }
  validates :content, presence: true

  has_many :replies
  belongs_to :user

  before_save :fill_content_html

  def fill_content_html
    self.content_html = Meetup::Markdown.render(self.content)
  end


  def Topic.update_content_sleep
    topic = Topic.first
    # 已经是悲观锁
    topic.with_lock do
      topic.content = SecureRandom.base64(64)
      sleep 10
      topic.save!
    end
  end

  def Topic.update_content
    topic = Topic.first
    # 已经是悲观锁
    topic.with_lock do
      topic.content = SecureRandom.base64(64)
      topic.save!
    end
  end

  def update_content(content)
    retry_times = 3

    begin
      self.update_content = content
      self.save!
    rescue ActiveRecord::StaleObjectError => e # 如果事务提交失败，那么 Rails 会抛一个 ActiveRecord::StaleObjectError 的异常。
      # 重试
      retry_times -= 1
      if retry_times > 0
        retry
      else
        raise e
      end
    rescue Exception => e
      raise e
    end
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def new
  end

  def index
    @total_count = Topic.count
    @topics = Topic.includes(:user).order("created_at desc").page(page).per(10)
  end

  def show
    @topic = Topic.find_by_id(params[:id])
    @replies = @topic.replies.includes(:user)
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id

    if @topic.save
      redirect_to topics_url
    else
      flash.now[:danger] = @topic.errors.full_messages
      render :new
    end
  end

  protected

  def topic_params
    params.require(:topic).permit(:title, :content)
  end

  def page
    params[:page] || 1
  end

end

app/controllers/v1/topics_controller.rb
class V1::TopicsController < V1::BaseController

  def index
    @topics = Topic.includes(:user).order("created_at desc").page(page).per(10)

    render json: {:data => @topics.as_json( :only => [:title, :content, :content_html, :created_at],
                                            :include => {:user => {:only => [:id, :name]}})}
  end


  protected
  def page
    params[:page] || 1
  end

end

app/helpers/topics_helper.rb
module TopicsHelper

  def topic_creator(topic)
    topic.user.try(:name)
  end

  def reply_creator(reply)
    reply.user.try(:name)
  end
end

app/views/topics/index.html.erb
<% provide(:title, "话题列表") %>

<div class="row">
  <div class="col-md-2"></div>

  <div class="col-md-8">
    <div class="topics panel panel-default">
      <div class="panel-heading">共发布 <%= @total_count %> 个话题</div>
        <div class="panel-body">
          <% @topics.each_with_index do |topic, index| %>
            <div class="topic media">
              <div class="infos media-body">
                <div class="title media-heading">
                  <a title="<%= topic.title %>" href="/topics/<%= topic.id %>"><%= topic.title %></a>
                </div>
                <div class="info">
                  <span><%= topic_creator(topic) %></span>
                  · 发布于
                  <span><%= time_tag(topic.created_at) %></span>
                </div>
              </div>
              <div class="count media-right">
                <a href="/topics/<%= topic.id %>#reply<%= topic.replies.count %>"><%= topic.replies.count %></a>
              </div>
            </div>
          <% end %>
        </div>

      <div class="panel-footer">
        <%= paginate @topics, :theme => 'twitter-bootstrap-3',
                              :pagination_class => "pagination-md" %>
      </div>
    </div>
  </div>

  <div class="col-md-2"></div>
</div>

app/views/topics/new.html.erb
<% provide(:title, "新建话题") %>

<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">

    <div class="panel-body">
      <%= form_for :topic, url: topics_path do |f| %>
        <div class="form-group topic-title">
          <input type="text" class="form-control" id="title" name='topic[title]' placeholder="话题标题">
        </div>

        <div class="form-group topic-content">
          <textarea class="form-control" rows="20" name='topic[content]' placeholder="话题内容，请使用markdown编辑"></textarea>
        </div>

        <div class="row">
          <div class="col-sm-3">
            <input type='submit' name='commit' value="保存" class="btn btn-primary btn-lg btn-block">
          </div>
          <div class="col-sm-2">
            <a href="/topics" class="btn btn-default btn-lg btn-block" role="button">取消</a>
          </div>
        </div>
      <% end %>

    </div>
  <div class="col-md-2"></div>
</div>

app/views/topics/show.html.erb
<% provide(:title, "话题详情") %>

<div class="row">
  <div class="col-md-2"></div>

  <div class="topic-detail col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading media">
        <div class="media-body">
          <h1 class="media-heading"><%= @topic.title %></h1>
          <div class="info">
            <span><%= topic_creator(@topic) %></span> · 发布于 <span><%= time_tag(@topic.created_at)%></span>
          </div>
        </div>

      </div>
      <div class="panel-body">
        <%= @topic.content_html.html_safe %>
      </div>
    </div>

    <% if @replies.count > 0 %>
      <div id="replies" class="panel panel-default">
        <div class="panel-heading">共收到 <%= @replies.count %> 条回复</div>

        <% @replies.each_with_index do |reply, index| %>
          <div class="reply" id="reply<%= index + 1 %>">
            <div class="infos">
              <div class="info">
                <span class="name"><%= reply_creator(reply) %></span>
                · #<%= index + 1 %> ·
                <span class="time"><%= time_tag(reply.created_at) %></span>
              </div>
              <div class="markdown">
                <%= reply.content_html.html_safe %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

    <div id="reply" class="panel panel-default">
      <div class="panel-heading">
        回复
      </div>
      <div class="panel-body">
        <%= form_tag("/topics/#{@topic.id}/replies",class: "new_reply", id: "new_reply", remote: true) do %>
          <div class="form-group">
            <textarea class="form-control" rows="5" name='reply[content]' placeholder="回复话题，请使用markdown编辑"></textarea>
          </div>
          <div class="row">
            <div class="col-sm-3">
              <button type='submit' name='commit' class="btn btn-primary btn-block">保存</button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-2"></div>
</div>